### PR TITLE
Fix check_ipa_replication

### PR DESCRIPTION
**Pull request by Popsiclestick**
Fix this slice so it gets the correct value.

### CODE REVIEW

**Comment by Popsiclestick** [comment]
This is to address issue #35

**Comment by pcurie** [comment]
It would be great if this PR could be merged, it indeed fix the check that is non-functional out of the box.

Thanks

**Comment by gardart** [comment]
thanks @Popsiclestick

**Comment by Popsiclestick** [comment]
No problem. Glad this helped.  👍

**Pull request merged**
